version: '3.7'
services:
  web:
    build: ./
    ports:
      - "3333:80"
    volumes:
      - ./logs:/logs
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: bai3ohdohT
      MYSQL_DATABASE: test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql